newPRWelcomeComment: |
  Hi there ğŸ‘‹

  Welcome on board! I'm the humble servant of Atolye15 ğŸ¤–

  Thank you for your contribution! ğŸ‘Š

  Here is my checklist. _Yep, I also have a checklist._

  - [X] ~Say thanks to the contributor of Checklist.~
  - [X] ~Notify Atolye15 crew.~
  - [X] ~Display Atolye15 crew's PR reviewing checklist.~

  If you're curious about Atolye15 crew's PR reviewing checklist here it is:
  - [ ] Check if PR is compatible with our [CoC](https://www.github.com/atolye15/checklist/blob/master/CODE_OF_CONDUCT.md)
  - [ ] If PR is irrelevant, assign it to the related person.
  - [ ] Review PR carefully to check if it fits Atolye15's standards. ğŸ§
  - [ ] Approve or Request Change.

  My service here is done for now. I'll do my best to have the Atolye15 crew accept your PR. ğŸ¤

  Ciao âœŒï¸

firstPRMergeComment: |
  Hi ğŸ‘‹
  It's me again, the humble servant of Atolye15 ğŸ¤–

  I have good news for you. Your PR has been merged ğŸ¥³

  Here is what will follow next;
  - [ ] Build Gatsby on Netlify. 
  - [ ] Publish artifacts to Netlify CDN. 
  - [ ] Go live! ğŸ‰

  Now you're the part of Atolye15 Checklist community.

  Thank you! ğŸ¤˜
